/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pe.proyecto.swing;

import com.pe.proyecto.bean.Departamento;
import com.pe.proyecto.bean.EscuelaConductor;
import com.pe.proyecto.bean.Response;
import com.pe.proyecto.interfaces.DepartamentoDAO;
import com.pe.proyecto.interfaces.EscuelaConductorDAO;
import com.pe.proyecto.persistencia.ConductorDAOImpl;
import com.pe.proyecto.persistencia.DepartamentoDAOImpl;
import com.pe.proyecto.util.JPanelMensaje;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author miche
 */
public class ConductorFormulario extends javax.swing.JFrame {

    /**
     * Creates new form ConductorFormulario
     */
    JPanelMensaje JPanel = new JPanelMensaje();
    private ConductorBandeja conductorBandeja;
    int TipoFormulario = 0;
    int IdConductorAux = 0;

    public void setConductorBandeja(ConductorBandeja conductorBandeja ){
        this.conductorBandeja = conductorBandeja;
    }
    public int getIdConductorAux() {
        return IdConductorAux;
    }

    public void setIdConductorAux(int IdConductorAux) {
        this.IdConductorAux = IdConductorAux;
    }
    public int getTipoFormulario() {
        return TipoFormulario;
    }

    public void setTipoFormulario(int TipoFormulario) {
        this.TipoFormulario = TipoFormulario;
    }
    
    public ConductorFormulario(){
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        //setUndecorated(true);
    }
    
    
    public void cargarEditar(EscuelaConductor obj){
        System.out.print(obj.toString());
        setIdConductorAux(obj.getId());
        
        EscuelaConductor escuela = ObtenerEscuelaPorId(obj.getId());
        
        
        txtCodDep.setText(escuela.getCodDep());
        txtCodPro.setText(escuela.getCodPro());
        txtCodDis.setText(escuela.getCodDis());
        txtNroRuc.setText(escuela.getNroRuc());
        txtNombre.setText(escuela.getNombreEstablecimiento());
        txtDireccion.setText(escuela.getDireccion());
        txtCorreo.setText(escuela.getCorreo());
        txtTelefono.setText(escuela.getTelefono());
        txtEstado.setText(escuela.getEstado());
        
        obtenerDepartamentos();
        
    }
    private void obtenerDepartamentos()
    {
        
        List<Departamento> departamentos = null;
        try{
            DepartamentoDAO depDAO = new DepartamentoDAOImpl();
            departamentos = depDAO.listarTodos();
      
            // Limpiar el JComboBox antes de agregar nuevos elementos
            cbDepartamentos.removeAllItems();

            // Agregar los departamentos al JComboBox
            for (Departamento dep : departamentos) {
                cbDepartamentos.addItem(dep.getNombreDepartamento());
            }
            
        } catch (Exception e) {
            JPanel.Error(e.getMessage());
        }            
    }
    private EscuelaConductor ObtenerEscuelaPorId(int id){
        EscuelaConductor escuela = new EscuelaConductor();
        try{
            EscuelaConductorDAO conductorDAO = new ConductorDAOImpl();
            escuela = conductorDAO.BuscarPorId(id);
      
        } catch (Exception e) {
            JPanel.Error(e.getMessage());
        }    
        return escuela;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFormulario = new javax.swing.JPanel();
        lComboCodDep = new javax.swing.JLabel();
        lComboCodPro = new javax.swing.JLabel();
        lComboCodDis = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lCorreo = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lEstado = new javax.swing.JLabel();
        txtCodDep = new javax.swing.JTextField();
        txtCodPro = new javax.swing.JTextField();
        txtCodDis = new javax.swing.JTextField();
        cbDepartamentos = new javax.swing.JComboBox<>();
        lNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lNroRuc = new javax.swing.JLabel();
        txtNroRuc = new javax.swing.JTextField();
        lDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFormulario.setBackground(new java.awt.Color(255, 255, 255));

        lComboCodDep.setText("Departamento : ");

        lComboCodPro.setText("Provincia : ");

        lComboCodDis.setText("Distrito : ");

        lCorreo.setText("Correo :");

        jLabel1.setText("Telefono :");

        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        lEstado.setText("Estado :");

        txtCodDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodDepActionPerformed(evt);
            }
        });

        txtCodPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProActionPerformed(evt);
            }
        });

        cbDepartamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lNombre.setText("Nombre :");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lNroRuc.setText("Nro Ruc :");

        txtNroRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroRucActionPerformed(evt);
            }
        });

        lDireccion.setText("Direccion :");

        javax.swing.GroupLayout PanelFormularioLayout = new javax.swing.GroupLayout(PanelFormulario);
        PanelFormulario.setLayout(PanelFormularioLayout);
        PanelFormularioLayout.setHorizontalGroup(
            PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormularioLayout.createSequentialGroup()
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormularioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFormularioLayout.createSequentialGroup()
                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lNroRuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lComboCodDep, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNroRuc)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                                            .addComponent(txtDireccion))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormularioLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lComboCodDis, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCodDis, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(134, 134, 134))))
                            .addGroup(PanelFormularioLayout.createSequentialGroup()
                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                                        .addComponent(txtCodDep, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lComboCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                                        .addComponent(lCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCorreo))
                                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTelefono))
                                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                                        .addComponent(lEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEstado)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        PanelFormularioLayout.setVerticalGroup(
            PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormularioLayout.createSequentialGroup()
                .addComponent(cbDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNroRuc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccion))
                .addGap(18, 18, 18)
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lComboCodDep)
                    .addComponent(lComboCodPro)
                    .addComponent(lComboCodDis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEstado)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConfirmar.setBackground(new java.awt.Color(0, 102, 153));
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(PanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(PanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
       
        String CodDep = txtCodDep.getText().trim();
        String CodPro = txtCodPro.getText().trim();
        String CodDis = txtCodDis.getText().trim();
        String NroRuc = txtNroRuc.getText().trim();
        String Nombre = txtNombre.getText().trim();
        String Direccion = txtDireccion.getText().trim();
        String Correo = txtCorreo.getText().trim();
        String Telefono = txtTelefono.getText().trim();
        String Estado = txtEstado.getText().trim();
        
        if(CodDep.isEmpty() || CodPro.isEmpty() || CodDis.isEmpty() || NroRuc.isEmpty() || Nombre.isEmpty() || Direccion.isEmpty() || Correo.isEmpty() || Telefono.isEmpty() || Estado.isEmpty() )      
        {
            JOptionPane.showMessageDialog(null,"Debe de ingresar todos los campos");
        }
        else{
            EscuelaConductorDAO conductorDAO = new ConductorDAOImpl();
            Response oValidaciones = new Response();
            EscuelaConductor obj = new EscuelaConductor();

            if(TipoFormulario == 2) obj.setId(getIdConductorAux());
            obj.setCodDep(CodDep);
            obj.setCodPro(CodPro);
            obj.setCodDis(CodDis);
            obj.setNroRuc(NroRuc);
            obj.setNombreEstablecimiento(Nombre);
            obj.setDireccion(Direccion);
            obj.setCorreo(Correo);
            obj.setTelefono(Telefono);
            obj.setEstado(Estado);

            try {
                oValidaciones = conductorDAO.Validaciones(obj);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Error : " + ex.getMessage());
                Logger.getLogger(ConductorFormulario.class.getName()).log(Level.SEVERE, null, ex);
            }

            if(oValidaciones.getResultadoBit())
                try {
                        if(TipoFormulario == 1)
                            conductorDAO.insertar(obj);
                        if(TipoFormulario == 2)
                            conductorDAO.actualizar(obj);
                        
                    ConductorBandeja Bandeja = new ConductorBandeja();
                    if(conductorBandeja != null)
                        conductorBandeja.ListarConductores();
                       
                    this.dispose();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,"Error : " + ex.getMessage());
                    Logger.getLogger(ConductorFormulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            else
                JOptionPane.showMessageDialog(null,"Error : " + oValidaciones.getResultadoDesc());        

           
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtNroRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroRucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroRucActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtCodProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProActionPerformed

    private void txtCodDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodDepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConductorFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConductorFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConductorFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConductorFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConductorFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFormulario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cbDepartamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lComboCodDep;
    private javax.swing.JLabel lComboCodDis;
    private javax.swing.JLabel lComboCodPro;
    private javax.swing.JLabel lCorreo;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lNroRuc;
    private javax.swing.JTextField txtCodDep;
    private javax.swing.JTextField txtCodDis;
    private javax.swing.JTextField txtCodPro;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroRuc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables


}
